//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BearFoods.BL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Bearfoods {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Bearfoods() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BearFoods.BL.Bearfoods", typeof(Bearfoods).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bär-BQ.
        /// </summary>
        internal static string BBQ {
            get {
                return ResourceManager.GetString("BBQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.openxmlformats-officedocument.wordprocessingml.document.
        /// </summary>
        internal static string ContentTypeWord {
            get {
                return ResourceManager.GetString("ContentTypeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Braten.
        /// </summary>
        internal static string Jus {
            get {
                return ResourceManager.GetString("Jus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BearFoods.BL.Vorlagen.Vorlage_Lieferschein.docx.
        /// </summary>
        internal static string LieferscheinPath {
            get {
                return ResourceManager.GetString("LieferscheinPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza.
        /// </summary>
        internal static string Pizza {
            get {
                return ResourceManager.GetString("Pizza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BearFoods.BL.Vorlagen.Vorlage_Rechnung.docx.
        /// </summary>
        internal static string RechnungPath {
            get {
                return ResourceManager.GetString("RechnungPath", resourceCulture);
            }
        }
    }
}
